version: '3.6'
services:

  hasura-cli-console:
    build: ./.docker-images/hasura-cli
    ports:
      - 9695:9695
    volumes:
      - ./${HASURA_PROJECT:-hasura-state}:/project
    command: > 
      hasura console 
        --log-level DEBUG 
        --address "hasura-cli-console" 
        --no-browser 
        --api-host https://9693-${GITPOD_WORKSPACE_ID}.${GITPOD_WORKSPACE_CLUSTER_HOST} 
        --api-port 443
        --endpoint https://8080-${GITPOD_WORKSPACE_ID}.${GITPOD_WORKSPACE_CLUSTER_HOST}
        --admin-secret ${HASURA_ADMIN_SECRET:-hasura}
    working_dir: /project
    restart: unless-stopped
    depends_on:
      hasura-engine:
        condition: service_healthy
    networks:
      - hasura

  hasura-cli-api:
    build: ./.docker-images/hasura-cli
    ports:
      - 9693:9693
    volumes:
      - ./${HASURA_PROJECT:-hasura-state}:/project
    command: >
      hasura console
        --log-level DEBUG
        --address "hasura-cli-api"
        --no-browser
        --endpoint http://hasura-engine:8080
        --admin-secret ${HASURA_ADMIN_SECRET:-hasura}
    working_dir: /project
    restart: unless-stopped
    depends_on:
      hasura-engine:
        condition: service_healthy
    networks:
      - hasura